# fraction of cases that are assumed to be among msm
msm_fraction: 0.15
# fraction of cases that present with symptoms
sti_symptoms:
  gc:
    male: 0.9
    female: 0.5
  chlamydia:
    male: 0.5
    female: 0.3
  syphilis:
    male: 0.67
    female: 0.5
  trichomoniasis:
    # doesn't matter since no male hiv cases are attributable to trichomoniasis
    male: 0.5
    female: 0.15
# not all art coverage is effective
# see https://www.thelancet.com/journals/laninf/article/PIIS1473309909703287/abstract
art_efficacy: 0.78
